### ISSUE TITLE
Post，对像复杂嵌套问题

### ISSUE THREAD

**Issue by liliping28** [NoBugBoy/YDoc#1]
当对像当中嵌套A对像，A对像在嵌套List实体，启动就会报错。经排查，这类RequestTypeMatchingSwagger，388行，//对象 先解析desc
            Class<?> declaringClass = declaredField.getClass();改成Class<?> declaringClass = declaredField.getType()；就可以了。感谢作者提供了这么方便的工具，省着自己录了。感谢

**Comment by NoBugBoy** [comment]
@liliping28  好的。才刚发了版1.0.2支持了原生swagger-bootstrap-ui，早点看到就一起上了。。

**Comment by liliping28** [comment]
大神什么时候可以支持无注解，期待使用。

**Comment by NoBugBoy** [comment]
@liliping28  本来想用注释的方式，可是runtime期间不支持，再想办法。

**Comment by liliping28** [comment]
那种javadoc的方式可以吗？这样字段上的注释，类上的注释，方法上的注释都可以拿的到。不知大神，可否考虑这个方案呢

**Comment by NoBugBoy** [comment]
@liliping28 考虑过，运行期间拿不到，不参与编译，用Doclet只能通过路径方式io去读。不是很方便

**Comment by liliping28** [comment]
是的，但是现在很多人写的话，都不会写name属性，直接给个路径。不通过javaDoc去拿的话，写时就要非常注意了，不是很方便

**Comment by NoBugBoy** [comment]
@liliping28  明白 close了哦
