### ISSUE TITLE
返回值泛型结构出现覆盖问题

### ISSUE THREAD

**Issue by cuiyuanjie** [NoBugBoy/YDoc#12]
我定义了一个R类，用于封装接口的返回对象，里面有error和data，**data是泛型**；
在controller中接口返回值使用 **R<User>、R<Teacher>**，ydoc可以正常解析，但从yapi上查看的**接口返回结构中User或Teacher谁在最后（swagger的definitions部分），页面展示的结构就是哪个对象的**； 
（将ydoc生产的swagger的json提取出来发现在 **defintions结构中对R中data的定义**只保留1个bean（要么是Teacher要么是User），而多个接口引用R的返回就导致展示返回值问题）

public R<User> getUser(Long uId) {}
public R<Teacher> getTeacher(Long tId) {}

public R<T> {
   private T data;
  .......
}

swagger json:
definitions部分：
**"R":{**"type": "object", "title": "R", "properties":{"data":{"description":"data", "$ref":"#/definitions/**Teacher**"}}}

接口定义部分：
paths：
   /getUser
      “responses”:
            schema: $ref: "**#/definitions/R**"
 /getTeacher
        “responses”:
            schema: $ref: "**#/definitions/R**"

**Comment by NoBugBoy** [comment]
嗯 确实只维护了一个单范型问题，这个我会解决一下

**Comment by NoBugBoy** [comment]
1.1.0 解决了这个问题 包已经上传 预计11.2号可以更新依赖
