### ISSUE TITLE
当controller 加入 shiro @RequiresAuthentication 注解时，  api扫描不到，无法生成文档

### ISSUE THREAD

**Issue by zhoukc** [NoBugBoy/YDoc#17]

**Comment by NoBugBoy** [comment]
你在controller上有没有requestmapping的外层路径，如果没有你加一下试试

**Comment by zhoukc** [comment]
加了的


| |
17195877391
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年12月9日 ***@***.***> 写道：

你在controller上有没有requestmapping的外层路径，如果没有你加一下试试

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by NoBugBoy** [comment]
所有文档都看不了了，还是只有加了注解的

**Comment by zhoukc** [comment]
加了权限注解的文档，看不了，其他没加的正常


| |
17195877391
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年12月9日 ***@***.***> 写道：

所有文档都看不了了，还是只有加了注解的

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by NoBugBoy** [comment]
好的 我抽时间看下啥问题..

**Comment by NoBugBoy** [comment]
shiro-spring 1.6.0版本
我加了那个注解没什么问题，是不是还配置了什么东西

**Comment by zhoukc** [comment]
我换个项目就可以了，版本一模一样，配置也一样


就加一个了统一响应结果的包装，不会构成影响






| |
17195877391
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年12月10日 ***@***.***> 写道：

shiro-spring 1.6.0版本
我加了那个注解没什么问题，是不是还配置了什么东西

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
