### ISSUE TITLE
无法生成返回数据

### ISSUE THREAD

**Issue by lxl233** [NoBugBoy/YDoc#27]
使用单体spring boot 2.6.2  
![image](https://user-images.githubusercontent.com/44200768/179343663-731cba98-d048-47ce-b12b-e3f1fa072a47.png)
图中接口的返回对象数据在yapi中为空

**Comment by lxl233** [comment]
> 1.1.6没出现这个问题 我能看看这个实体吗

![image](https://user-images.githubusercontent.com/44200768/179481194-677af495-4522-44ab-85f9-0149e70dc754.png)

**Comment by NoBugBoy** [comment]
修复了 等下个版本一起升级

**Comment by lxl233** [comment]
> 修复了 等下个版本一起升级

能问下原因吗。

**Comment by NoBugBoy** [comment]
没有单独处理返回值为简单object类型，处理一下加到Definitions中就好了

**Comment by lxl233** [comment]
> 没有单独处理返回值为简单object类型，处理一下加到Definitions中就好了

下个版本打算什么时候上线哦。

**Comment by NoBugBoy** [comment]
> > 没有单独处理返回值为简单object类型，处理一下加到Definitions中就好了
> 
> 下个版本打算什么时候上线哦。

Emm   我在多支持几个不常用的类型 然后final版本也需要维护下 可能得几天吧 毕竟我一个人维护（手动狗头）
