### ISSUE TITLE
knife4j-spring-ui-2.0.8 支持不?

### ISSUE THREAD

**Issue by siaron** [NoBugBoy/YDoc#4]
可以保存接口版本的变化历史吗? 从v1-v2 接口改变了什么. 如果有这个功能觉得会更好.

**Comment by NoBugBoy** [comment]
@siaron  knife4j下个版本考虑集成进来，变化历史的话如果你能接受多一个mongodb的话是可以的，但是问题是什么地方展示变更呢。原生swagger和yapi似乎都不太支持。可能需要造一个。
