### ISSUE TITLE
响应泛型对象时，Yapi不显示泛型属性

### ISSUE THREAD

**Issue by luochaocao** [NoBugBoy/YDoc#8]
响应泛型对象：
public class ResultModel<T> implements Serializable {
    private int code;
    private String text;
    private T data;
}

Yapi显示：
code | integer | 非必须 |   | http状态码 |  
data  | object  | 非必须 |   | data            | 备注: data
text   | string   | 非必须 |   | 描述

问题如下：
data泛型是个VO，yapi上不显示VO以下属性，请问这个怎么解决？

**Comment by NoBugBoy** [comment]
建议使用Object 但是这确实是个问题 我解决一下

**Comment by NoBugBoy** [comment]
1.0.8会解决这个问题，不支持多泛型 单个泛型是可以的
